### ISSUE TITLE
add support for 360-day calendars 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#181]
Currently our pipeline only supports leap day and no-leap day GCM calendars. The HadGEM and KACE models (Hadley Center and NIMS-KMA, respectively) both have 360_day calendars, thus we need to add support for those calendars in our pipeline. Current proposal is to use the `xclim` `convert_calendar` function for now.

**Comment by dgergel** [comment]
@emileten I think we fixed this and can close this now?

**Comment by emileten** [comment]
Let's leave this open until we're sure it didn't cause #439. I guess that's why you reopened it.

**Comment by brews** [comment]
We added 360 calendar support in dodola in v0.12.0 and fixed it up in v0.13.0. I think all the clean-cmip6 steps are running with dodola:0.8.0. 

Wouldn't this be a matter of just upgrading those cleaning step containers? I can put this into a PR to move things forward.

Technically we would have 360 support it's just that in the case of KACE (ha ha; #439 ), the calendar conversion or the input data might be buggy. Right?

**Comment by emileten** [comment]
@brews I think you were writing in #439 that you used `dodola:dev` in the test run. In which case, is this going to make a difference? 

Regardless, I guess it's good to update these containers!

**Comment by brews** [comment]
@emileten Last night I tried the work described in #439 with `dodola:0.16.1` and KACE still throws the same error, but I _think_ I've only seen this particular error with KACE.

This issue is just for adding 360 day support generally, so I'm close this with PR #527 and then let's debug KACE in #439.

Let me know if you feel otherwise about this.

**Comment by emileten** [comment]
Oh I see what you mean @brews. No I'm fine with closing this. 

Yes we've only seen this bug with KACE, but that's the only model that triggers the line of codes from the 360-day support addition. 

Let's work on that in #439 !
